### ISSUE TITLE
pose detection의 API화 문제

### ISSUE THREAD

**Issue by Seunghui98** [Eye-Remocon/Pose_Detection#1]
현재 Teachable machine을 통해 학습한 pose detection 모델을 Github 에 호스팅 해두었습니다.
[링크](https://eye-remocon.github.io/Pose_Detection/)
위 링크를 클릭하시면 테스트할 수 있는 사이트로 연결되고, start를 누르면 웹캠을 이용하여 3가지 포즈로 분류합니다.
다음은 3가지 이미지에 대해서 잘 분류가 되는지 테스트한 결과입니다.
<img width="394" alt="스크린샷 2021-08-06 오후 11 40 15" src="https://user-images.githubusercontent.com/54658745/128530644-19154441-adc9-429a-a6a6-54e9a5b3c802.png">  
<img width="439" alt="스크린샷 2021-08-06 오후 11 41 05" src="https://user-images.githubusercontent.com/54658745/128530649-fd774cc6-2866-4aa3-882c-b1214eabba53.png">  
<img width="453" alt="스크린샷 2021-08-06 오후 11 41 51" src="https://user-images.githubusercontent.com/54658745/128530658-f8d5a49b-5087-4361-9eb7-6018c65a2488.png">  

위 3가지 동작들 잘 분류가 되는 것을 확인할 수 있습니다.
그러나 이 pose detection을 우리가 잘 적용할 수 있게 API 화 하는데 문제가 있습니다.

일단 현재 저희가 만들어가는 서비스 흐름 중 카메라모듈을 통해 캡쳐되는 이미지를 pose detection 에 보내서
사람인식 되었다면 위 세 가지 동작(기절, 식사, 박수)로 만약 분류되는지 확인한 후,  그 pose의 값을 리턴할 수 있도록 API를 설계하려고 합니다.

그러나 코드가 html안에 동작하는 javascript 코드여서 어떻게 바꿔야 할지 감이 오지 않습니다. 
일단 생각하는 게 클라이언트부분에서 캡쳐된 이미지에서 사람이 인식되었다면 해당 이미지를 서버로 post 요청하고
javascript가 포함된 서버에서 해당 이미지를 포즈 분류하고 ( 해당 포즈의 확률이 1인 경우에만 )
해당 포즈값을 클라이언트로 반환하여 분류된 포즈를 이용하는 방식으로 하고 싶습니다.
클라이언트의 요청을 받아서 포즈 분석 후 값을 반환하는 부분이 node.js를 이용한다면 어떻게 구현해야할 지 잘 모르겠습니다.
이 부분에 대해서 좋은 의견 있으시다면 조언 부탁드립니다 !!

또한, 문제가 해당 동작이 아닌데도, 웹캠으로 동작을 하다보면 분류가 잘 안되는 경우가 있는데 이 부분에 대해서는
따로 학습이미지를 선별하여서 다시 학습하는 게 좋을까요?? 아니면 위에 부분을 해결하고 뒤에 성능 높이기 위해 노력해야할 때
다시 학습시키는 게 나을까요 ?

**Comment by Seunghui98** [comment]
@t25kim @lspc678 @Ryumaker @woniiiii 

해당 이슈에 대해서 조언 부탁드립니다 !!!!

**Comment by Seunghui98** [comment]
@t25kim @lspc678 @Ryumaker @woniiiii 

[코드](https://github.com/Eye-Remocon/Pose_Detection/blob/37f13e68ce8419d6fd61f9cbcdabc38ba374ecf5/index.html#L61)  

대충 html 속 body 태그 안에 코드 흐름이
버튼 클릭 -> 웹캡 설치 및 웹캠 무한루프 돌면서 실행 -> 웹캠에서 해당 부분에서 posenet이용하여  17개의 골격구조 파악
-> 해당 골격구조을 통해 3가지 포즈로 분류 실행 -> 예측값 출력

이 흐름인 것 같고 위의 코드 라인에서 웹캠에서 video가 아닌 image도 예측이 된다고 하니 저 부분을 바꿔보려 생각했지만, 
혹시 이게 pose 관련이니깐 웹캠을 이용해서 실시간으로 pose 를 분석하는 코드가 나을까요 ?

**Comment by tiokim** [comment]
@Seunghui98 nodejs로 하면 될 듯 한데 https://www.npmjs.com/package/@sashido/teachablemachine-node 가 도움이 될 수 있을까요?
